function [methodinfo,structs,enuminfo,ThunkLibName]=dvsenseBridgePrototype
%DVSENSEBRIDGEPROTOTYPE Create structures to define interfaces found in 'dvsense_bridge'.

%This function was generated by loadlibrary.m parser version  on Tue Aug 18 11:19:19 2026
%perl options:'dvsense_bridge.i -outfile=dvsenseBridgePrototype.m -thunkfile=dvsense_bridge_thunk_pcwin64.c -header=dvsense_bridge.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'dvsense_bridge_thunk_pcwin64');
%  int dvsense_open ( const char * serial ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='dvsense_open'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  const char * dvsense_discover_cameras_json ( void ); 
fcns.thunkname{fcnNum}='cstringvoidThunk';fcns.name{fcnNum}='dvsense_discover_cameras_json'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  const char * dvsense_list_stale_helpers_json ( void ); 
fcns.thunkname{fcnNum}='cstringvoidThunk';fcns.name{fcnNum}='dvsense_list_stale_helpers_json'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int dvsense_terminate_stale_helpers ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='dvsense_terminate_stale_helpers'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int dvsense_close ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='dvsense_close'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int dvsense_start ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='dvsense_start'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int dvsense_stop ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='dvsense_stop'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int dvsense_set_batch_time ( uint64_t window_us ); 
fcns.thunkname{fcnNum}='int32uint64Thunk';fcns.name{fcnNum}='dvsense_set_batch_time'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64'};fcnNum=fcnNum+1;
%  int dvsense_set_display_window ( uint64_t window_us ); 
fcns.thunkname{fcnNum}='int32uint64Thunk';fcns.name{fcnNum}='dvsense_set_display_window'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64'};fcnNum=fcnNum+1;
%  int dvsense_set_roi ( int32_t x , int32_t y , int32_t width , int32_t height ); 
fcns.thunkname{fcnNum}='int32int32int32int32int32Thunk';fcns.name{fcnNum}='dvsense_set_roi'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'int32', 'int32', 'int32', 'int32'};fcnNum=fcnNum+1;
%  int dvsense_read_events ( uint16_t * x , uint16_t * y , uint8_t * polarity , uint64_t * timestamp , uint32_t capacity , uint32_t * count ); 
fcns.thunkname{fcnNum}='int32voidPtrvoidPtrvoidPtrvoidPtruint32voidPtrThunk';fcns.name{fcnNum}='dvsense_read_events'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint16Ptr', 'uint16Ptr', 'uint8Ptr', 'uint64Ptr', 'uint32', 'uint32Ptr'};fcnNum=fcnNum+1;
%  int dvsense_read_frame ( uint8_t * frame , uint32_t capacity , uint32_t * width , uint32_t * height ); 
fcns.thunkname{fcnNum}='int32voidPtruint32voidPtrvoidPtrThunk';fcns.name{fcnNum}='dvsense_read_frame'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint8Ptr', 'uint32', 'uint32Ptr', 'uint32Ptr'};fcnNum=fcnNum+1;
%  const char * dvsense_get_camera_info_json ( void ); 
fcns.thunkname{fcnNum}='cstringvoidThunk';fcns.name{fcnNum}='dvsense_get_camera_info_json'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  const char * dvsense_get_tool_parameters_json ( void ); 
fcns.thunkname{fcnNum}='cstringvoidThunk';fcns.name{fcnNum}='dvsense_get_tool_parameters_json'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int dvsense_set_parameter ( const char * tool , const char * name , const char * type , const char * value ); 
fcns.thunkname{fcnNum}='int32cstringcstringcstringcstringThunk';fcns.name{fcnNum}='dvsense_set_parameter'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'cstring', 'cstring', 'cstring'};fcnNum=fcnNum+1;
%  int dvsense_start_recording ( const char * path ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='dvsense_start_recording'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  int dvsense_stop_recording ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='dvsense_stop_recording'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  const char * dvsense_last_value ( void ); 
fcns.thunkname{fcnNum}='cstringvoidThunk';fcns.name{fcnNum}='dvsense_last_value'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  const char * dvsense_last_error ( void ); 
fcns.thunkname{fcnNum}='cstringvoidThunk';fcns.name{fcnNum}='dvsense_last_error'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
methodinfo=fcns;